Qshop/Buyer/urls.py
from django.urls import path, re_path
from Buyer import views

urlpatterns = [
    path('register/', views.register),
    path('login/', views.login),
    path('logout/', views.logout),
    path('index/', views.index),
    path('goodslist/', views.goods_list),
    re_path(r'goodsdetail/(?P<idn>\d+)/', views.goods_detail),

    path('personalcart/', views.personal_cart),
    path('addgoods/', views.buyer_add_goods),

    path('ajaxaddreduce/', views.ajax_add_reduce),
    path('ajaxaddgoods/', views.ajax_buyer_add_goods),

    path('neworderinfo/', views.new_order_info),
    path('alipay/', views.ali_pay),
    path('payinfo/', views.pay_info),
    path('buserinfo/', views.buyer_user_info),
    re_path(r'buserallorder/(?P<page>\d)/', views.buyer_user_all_order),

]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from Buyer import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index),
    re_path(r'^seller/', include(('Seller.urls', 'Seller'), namespace='Seller')),
    re_path(r'^buyer/', include(('Buyer.urls', 'Buyer'), namespace='Buyer')),
]

Qshop/Buyer/models.py
from django.db import models
from Seller.models import SellerUser, Goods


# Create your models here.
class BuyerUser(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=32)

    username = models.CharField(max_length=32, null=True, blank=True)
    phone_number = models.CharField(max_length=32, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=32, null=True, blank=True)
    photo = models.ImageField(upload_to='buyer/images', null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    user_type = models.IntegerField(default=0)  # 0 买家 1 卖家 2 管理者


class CartOne(models.Model):
    """
    购物车
    """
    buy_user = models.ForeignKey(to='BuyerUser', on_delete=models.CASCADE)
    goods = models.ForeignKey(to=Goods, on_delete=models.CASCADE)
    goods_unit = models.CharField(max_length=32, default='500g')
    count = models.IntegerField()
    total_price = models.FloatField(null=True, blank=True)
    status = models.IntegerField(default=1)  # 1 表示存在 0 表示已删除
    date = models.DateTimeField(auto_now=True)


class Order(models.Model):
    order_num = models.CharField(max_length=32)
    order_date = models.DateTimeField(auto_now=True)
    order_status = models.IntegerField(default=0)  # 0 表示未支付， 1 表示已支付
    order_total = models.FloatField(blank=True, null=True)
    order_user = models.ForeignKey(to='BuyerUser', on_delete=models.CASCADE)


class OrderInfo(models.Model):
    """
    订单详情表
    订单状态：
    0 未付款
    1 已付款
    2 待发货
    3 完成
        确认收货
        拒收
        退款
    """
    order_id = models.ForeignKey(to='Order', on_delete=models.CASCADE)
    store_id = models.ForeignKey(to=SellerUser, on_delete=models.CASCADE)

    goods_id = models.IntegerField()
    goods_name = models.CharField(max_length=32)
    goods_picture = models.CharField(max_length=32)
    goods_count = models.IntegerField()
    goods_price = models.FloatField()
    goods_total_price = models.FloatField()
    status = models.IntegerField(default=0)

Qshop/Buyer/forms.py
from django import forms


class Register(forms.Form):

    email = forms.EmailField()
    password = forms.CharField(max_length=32)
    username = forms.CharField(max_length=32)
    # phone_number = forms.CharField(max_length=32)
    # gender = forms.CharField(max_length=32)
    # age = forms.IntegerField()
    # photo = forms.ImageField()
    # address = forms.Textarea()

Qshop/Buyer/views.py
import time
import random
import hashlib
from alipay import AliPay

from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse

from Buyer import models, forms
from Seller.models import GoodsType, Goods
from Qshop.settings import ALIPAY_PUBLIC, APP_PRIVATE, ALIPAY_URL


def set_pwd(password):
    SALT = b'bestwish'
    md5 = hashlib.md5(SALT)
    md5.update(password.encode('utf-8'))
    ret = md5.hexdigest()
    return ret


def login_valid(func):
    def inner(request, *args, **kwargs):
        cookie_email = request.COOKIES.get('buyer_user_email')
        session_email = request.session.get('buyer_user_email')
        if cookie_email and cookie_email == session_email:
            return func(request, *args, **kwargs)
        else:
            return redirect('/buyer/login/')

    return inner


def random_str():
    string = 'abcdefghigklmnopqrstuvwxyz'
    ret = ''
    for i in range(4):
        ret += random.choice(string)
    return ret

# Create your views here.


def register(request):
    err_msg = ''
    if request.method == 'POST':
        email = request.POST.get('email')
        if email:
            password = request.POST.get('password')
            repassword = request.POST.get('repassword')
            if password == repassword:
                register_data = forms.Register(request.POST)
                if register_data.is_valid():
                    data_clean = register_data.cleaned_data
                    clean_email = data_clean.get('email')
                    user = models.BuyerUser.objects.filter(email=clean_email).first()
                    if not user:
                        new_user = models.BuyerUser()
                        new_user.email = clean_email
                        clean_password = data_clean.get('password')
                        new_user.password = set_pwd(clean_password)
                        new_user.username = data_clean.get('username')
                        new_user.save()
                        return redirect('/buyer/login/')
                    else:
                        err_msg = '邮箱已被注册，请登录'
                else:
                    err_msg = '注册信息不完整'
            else:
                err_msg = "密码不一致"
        else:
            err_msg = '邮箱不能为空'

    return render(request, 'buyer/register.html', locals())


def login(request):
    err_msg = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        login_user = models.BuyerUser.objects.filter(username=username).first()
        if login_user:
            db_password = login_user.password
            password = set_pwd(request.POST.get('password'))
            if password == db_password:
                response_obj = redirect('/buyer/index/')
                response_obj.set_cookie('buyer_username', value=login_user.username)
                response_obj.set_cookie('buyer_user_id', value=login_user.id)
                response_obj.set_cookie('buyer_user_email', value=login_user.email)
                request.session['buyer_user_email'] = login_user.email
                return response_obj
            else:
                err_msg = "两次输入密码不一致"
        else:
            err_msg = "用户名不存在"

    return render(request, 'buyer/login.html', locals())


def logout(request):
    url = request.META.get('HTTP_REFERER', '/')
    response_obj = redirect(url)
    response_obj.delete_cookie('buyer_username')
    response_obj.delete_cookie('buyer_user_email')
    del request.session['buyer_user_email']
    return response_obj


def index(request):
    buyer_user_id = request.COOKIES.get('buyer_user_id')
    if buyer_user_id:
        buyer_user = models.BuyerUser.objects.get(id=int(buyer_user_id))
    goods_type = GoodsType.objects.all()
    result = []
    for gt in goods_type:
        goods = gt.goods_set.order_by('-goods_pro_time')
        if len(goods) >= 4:
            goods_list = goods[:4]
            result.append({
                'gt': gt,
                'goods_list': goods_list
            })

    return render(request, 'buyer/index.html', locals())


def goods_list(request):
    ty = request.GET.get('ty')
    kw = request.GET.get('kw')
    goods_display = []
    if ty == 't':
        gt = GoodsType.objects.get(id=int(kw))
        goods_display = gt.goods_set.order_by('-goods_pro_time')
    elif ty == 'k':
        goods_display = Goods.objects.filter(goods_name__contains=kw).order_by('-goods_pro_time')

    return render(request, 'buyer/goodslist.html', locals())


def goods_detail(request, idn):
    goods = Goods.objects.get(id=int(idn))
    return render(request, 'buyer/goodsdetail.html', locals())


@login_valid
def buyer_add_goods(request):
    buyer_user_id = int(request.COOKIES.get('buyer_user_id'))
    goods_id = request.GET.get('goods_id')
    count = request.GET.get('count')
    if goods_id and count:
        buy_user = models.BuyerUser.objects.get(id=int(buyer_user_id))
        buy_user_cart = buy_user.cartone_set.filter(status=1)
        for g in buy_user_cart:
            if g.goods.id == int(goods_id):
                g.count += int(count)
                g.save()
                break
        else:
            goods = Goods.objects.get(id=int(goods_id))
            new_add_cart = models.CartOne()
            new_add_cart.buy_user = buy_user
            new_add_cart.goods = goods
            new_add_cart.count = int(count)
            new_add_cart.save()

    url = request.META.get('HTTP_REFERER', '/')
    return redirect(url)


@login_valid
def ajax_buyer_add_goods(request):
    result = {
        'code': 200,
        'data': '',
    }
    if request.method == 'POST':
        buyer_user_id = int(request.COOKIES.get('buyer_user_id'))
        goods_id = request.POST.get('goods_id')
        count = request.POST.get('count', 1)
        buy_user = models.BuyerUser.objects.get(id=int(buyer_user_id))
        buy_user_cart = buy_user.cartone_set.filter(status=1)
        for g in buy_user_cart:
            if g.goods.id == int(goods_id):
                g.count += int(count)
                goods = Goods.objects.get(id=int(goods_id))
                if g.count > goods.goods_count:
                    g.count = goods.goods_count
                    result['data'] += '修改添加商品数量为该商品库存量'
                g.total_price = round(goods.goods_price * g.count, 2)
                g.save()
                break
        else:
            goods = Goods.objects.get(id=int(goods_id))
            new_add_cart = models.CartOne()
            new_add_cart.buy_user = buy_user
            new_add_cart.goods = goods
            new_add_cart.count = int(count)
            new_add_cart.total_price = round(goods.goods_price * new_add_cart.count, 2)
            new_add_cart.save()
        result['data'] += "加入购物车成功"
    else:
        result['code'] = 500
        result['data'] += "加入购物车失败"
    return JsonResponse(result)


@login_valid
def ajax_add_reduce(request):
    result = {
        'code': 200,
        'data': '',
    }
    buyer_user_id = int(request.COOKIES.get('buyer_user_id'))
    goods_id = int(request.GET.get('goods_id'))
    count = int(request.GET.get('count'))
    buy_user = models.BuyerUser.objects.get(id=int(buyer_user_id))
    cartone_obj = buy_user.cartone_set.get(goods_id=goods_id)
    if count <= 0:
        count = 0
    elif count >= cartone_obj.goods.goods_count:
        count = cartone_obj.goods.goods_count
    cartone_obj.count = count
    cartone_obj.total_price = cartone_obj.goods.goods_price * count
    cartone_obj.save()
    result['data'] = '商品数量修改成功'
    return JsonResponse(result)


@login_valid
def personal_cart(request):
    buyer_user_id = int(request.COOKIES.get('buyer_user_id'))
    buy_user = models.BuyerUser.objects.get(id=int(buyer_user_id))
    cart_goods = buy_user.cartone_set.filter(status=1, count__gte=1).order_by('-date')
    count = len(cart_goods)

    return render(request, 'buyer/personalcart.html', locals())


@login_valid
def buyer_user_info(request):
    return render(request, 'buyer/buyeruserinfo.html', locals())


@login_valid
def buyer_user_all_order(request,page=1):
    page = int(page)
    page_size = 6
    buyer_user_id = int(request.COOKIES.get('buyer_user_id'))
    buyer_user = models.BuyerUser.objects.get(id=buyer_user_id)
    orders = buyer_user.order_set.all().order_by('-order_date')
    orders_page = Paginator(orders, page_size)
    order_list = orders_page.page(page)
    page_range = list(orders_page.page_range)

    page_prev = page - 1  # 上一页
    page_next = page + 1  # 下一页
    if page_prev < 1:
        page_prev = 1
    if page_next > orders_page.num_pages:  # 总页数
        page_next = orders_page.num_pages

    return render(request, 'buyer/buyerallorder.html', locals())


# 单个提交订单 和 购物车合并
@login_valid
def new_order_info(request):
    goods_info = []
    yun_fee = 6
    total_fee = 0
    buyer_user_id = int(request.COOKIES.get('buyer_user_id'))
    request_data = request.GET
    goods_id = request_data.get('goods_id')
    count = request_data.get('count')
    if goods_id and count:
        goods_info.append((int(goods_id), int(count)))
    for k, v in request_data.items():
        if k.startswith('check_'):
            goods_id = k.rsplit('_', 1)[1]
            count = request_data.get('count_' + goods_id)
            goods_info.append((int(goods_id), int(count)))
    if request_data:
        new_order = models.Order()
        new_order.order_num = time.strftime('%Y%m%d%H%M%S') + random_str()
        new_order.order_user = models.BuyerUser.objects.get(id=buyer_user_id)
        new_order.save()

        for goods_id, count in goods_info:
            goods = Goods.objects.get(id=int(goods_id))
            new_order_info = models.OrderInfo()

            new_order_info.order_id = new_order
            new_order_info.store_id = goods.goods_store
            new_order_info.goods_id = int(goods_id)

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block tilte %}天天生鲜-首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
    {% block style %}
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.COOKIES.buyer_username %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ request.COOKIES.buyer_username }}</em>
                        <span>|</span>
                        <a href="/buyer/logout/">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="/buyer/login/">登录</a>
                        <span>|</span>
                        <a href="/buyer/register/">注册</a>
                    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/buyer/buserinfo/">用户中心</a>
					<span>|</span>
					<a href="/buyer/personalcart/">我的购物车</a>
					<span>|</span>
					<a href="/buyer/buserallorder/1">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% block search %}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
			<input id="search" type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="search()">
		</div>
		<div class="guest_cart fr">
			<a href="/buyer/personalcart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">100</div>
		</div>
	</div>
    {% endblock %}

    {% block nav %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="/buyer/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% endblock %}

    {% block content %}

    {% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2019 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>#}
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		};
		function search() {
            let kw = $("#search").val();
            let url = "/buyer/goodslist/?ty=k&kw=" + kw;
            window.location.href = url;
        }
	</script>

    {% block script %}
    {% endblock %}
</body>
</html>

Qshop/Buyer/templates/buyer/buyerallorder.html
{% extends 'buyer/base.html' %}

{% block tilte %}
    用户中心
{% endblock %}

{% block search %}

    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input id="search" type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="search()">
		</div>
	</div>
{% endblock %}

{% block nav %}
{% endblock %}

{% block content %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/buyer/buserinfo/">· 个人信息</a></li>
				<li><a href="/buyer/buserallorder/1" class="active">· 全部订单</a></li>
				<li><a href="">· 收货地址</a></li>
			</ul>
		</div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in order_list %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.order_date }}</li>
                <li class="col02">订单号：{{ order.order_num }}</li>
                {% ifequal order.order_status 0 %}
                <li class="col02 stress">待付款</li>
                {% endifequal %}
                {% ifequal order.order_status 1 %}
                <li class="col02 stress">已付款</li>
                {% endifequal %}
            </ul>

            <table class="order_list_table w980">
                <tbody>
                    <tr>
                        <td width="55%">
                            {% for goods in order.orderinfo_set.all %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="/static/{{ goods.goods_picture }}"></li>
                                <li class="col02">{{ goods.goods_name }}<em>{{ goods.goods_price }}元/500g</em></li>
                                <li class="col03">{{ goods.goods_count }}</li>
                                <li class="col04">{{ goods.goods_total_price }}元</li>
                                {% ifequal goods.status 0 %}
                                <li class="col05">待付款</li>
                                {% endifequal %}
                                {% ifequal goods.status 1 %}
                                <li class="col05">待发货</li>
                                {% endifequal %}
                                {% ifequal goods.status 2 %}
                                <li class="col05">确认收货</li>
                                {% endifequal %}
                                {% ifequal goods.status 3 %}
                                <li class="col05">评价</li>
                                {% endifequal %}
                                {% ifequal goods.status 4 %}
                                <li class="col05">已完成</li>
                                {% endifequal %}
                            </ul>
                            {% endfor %}
                        </td>

                        <td width="15%">{{ order.order_total }}元</td>
                        {% ifequal order.order_status 0 %}
                        <td width="15%">待付款</td>
                        <td width="15%"><a href="/buyer/alipay/?order_num={{ order.order_num }}&total_fee={{ order.order_total }}&subject={{ order.orderinfo_set.first.goods_name }}" class="oper_btn">去付款</a></td>
                        {% endifequal %}
                        {% ifequal order.order_status 1 %}
                        <td width="15%">已付款</td>
                        <td width="15%"><a href="#" class="oper_btn">查看详情</a></td>
                        {% endifequal %}
                    </tr>
                </tbody>
            </table>
            {% endfor %}

            <div class="pagenation">
                <a href="/buyer/buserallorder/{{ page_prev }}">&lt;上一页</a>
                {% for p in page_range %}
                <a href="/buyer/buserallorder/{{ p }}">{{ p }}</a>
                {% endfor %}
                <a href="/buyer/buserallorder/{{ page_next }}">下一页&gt;</a>
            </div>
		</div>
	</div>

{% endblock %}

Qshop/Buyer/templates/buyer/buyeruserinfo.html
{% extends 'buyer/base.html' %}

{% block tilte %}
    用户中心
{% endblock %}

{% block search %}

    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input id="search" type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="search()">
		</div>
	</div>
{% endblock %}

{% block nav %}
{% endblock %}

{% block content %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/buyer/buserinfo/" class="active">· 个人信息</a></li>
				<li><a href="/buyer/buserallorder/1">· 全部订单</a></li>
				<li><a href="">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>18210569700</li>
                <li><span>联系方式：</span>18210569700</li>
                <li><span>联系地址：</span>北京市昌平区</li>
            </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    <li>
                        <a href="detail.html"><img src="/static/buyer/images/goods/goods003.jpg"></a>
                        <h4><a href="detail.html">大兴大棚草莓</a></h4>
                        <div class="operate">
                            <span class="prize">￥16.80</span>
                            <span class="unit">16.80/500g</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>

                    <li>
                        <a href="#"><img src="/static/buyer/images/goods/goods004.jpg"></a>
                        <h4><a href="#">吐鲁番梨光杏</a></h4>
                        <div class="operate">
                            <span class="prize">￥5.50</span>
                            <span class="unit">5.50/500g</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>

                    <li>
                        <a href="#"><img src="/static/buyer/images/goods/goods005.jpg"></a>
                        <h4><a href="#">黄肉桃</a></h4>
                        <div class="operate">
                            <span class="prize">￥10.00</span>
                            <span class="unit">10.00/500g</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>

                    <li>
                        <a href="#"><img src="/static/buyer/images/goods/goods006.jpg"></a>
                        <h4><a href="#">进口西梅</a></h4>
                        <div class="operate">
                            <span class="prize">￥28.80</span>
                            <span class="unit">28.8/500g</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>

                    <li>
                        <a href="#"><img src="/static/buyer/images/goods/goods007.jpg"></a>
                        <h4><a href="#">香梨</a></h4>
                        <div class="operate">
                            <span class="prize">￥6.45</span>
                            <span class="unit">6.45/500g</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                </ul>
            </div>
		</div>
	</div>

{% endblock %}

Qshop/Buyer/templates/buyer/orderinfo.html
{% extends 'buyer/base.html' %}


{% block tilte %}
    订单信息
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input id="search" type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="search()">
		</div>
	</div>
{% endblock %}



{% block nav %}
{% endblock %}

{% block content %}

    <h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style">
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" checked>
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for goods in new_order.orderinfo_set.all %}
            <ul class="goods_list_td clearfix">
                <li class="col01">1</li>
                <li class="col02"><img src="/static/{{ goods.goods_picture }}"></li>
                <li class="col03">{{ goods.goods_name }}</li>
                <li class="col04">500g</li>
                <li class="col05">{{ goods.goods_price }}元</li>
                <li class="col06">{{ goods.goods_count }}</li>
                <li class="col07">{{ goods.goods_total_price }}元</li>
            </ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b id="goods_fee">{{ new_order.order_total }}元</b></div>
			<div class="transit">运费：<b>{{ yun_fee }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_fee }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="/buyer/alipay/?order_num={{ new_order.order_num }}&total_fee={{ total_fee }}&subject={{ new_order_info.goods_name }}" id="order_btn">提交订单</a>
	</div>


{% endblock %}

{% block script %}
    <script type="text/javascript">
    </script>
{% endblock %}